/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import controller.Controller;
import forme.model.ModelTabelePoruka;
import java.awt.Point;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.Admin;
import model.Poruka;
import server.PokreniServer;

/**
 *
 * @author PC
 */
public class ServerskaForma extends javax.swing.JFrame {
    private Admin admin = Controller.getInstance().getAdmin();
    private PokreniServer ps;
    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        initComponents();
        jLabelAdmin.setText("Zdravo, " + admin.toString());
        jButtonZaustavi.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAdmin = new javax.swing.JLabel();
        jButtonPokreni = new javax.swing.JButton();
        jButtonZaustavi = new javax.swing.JButton();
        jButtonUnesi = new javax.swing.JButton();
        jButtonPrikaziPoruke = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePoruke = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAdmin.setText("jLabel1");

        jButtonPokreni.setText("Pokreni Server");
        jButtonPokreni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPokreniActionPerformed(evt);
            }
        });

        jButtonZaustavi.setText("Zaustavi server");
        jButtonZaustavi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZaustaviActionPerformed(evt);
            }
        });

        jButtonUnesi.setText("Unesi Korisnika");
        jButtonUnesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUnesiActionPerformed(evt);
            }
        });

        jButtonPrikaziPoruke.setText("Prikazi Poruke");
        jButtonPrikaziPoruke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrikaziPorukeActionPerformed(evt);
            }
        });

        jTablePoruke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePoruke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePorukeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePoruke);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonPokreni)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonZaustavi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonUnesi)
                        .addGap(76, 76, 76)
                        .addComponent(jButtonPrikaziPoruke, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPokreni)
                    .addComponent(jButtonZaustavi)
                    .addComponent(jButtonUnesi)
                    .addComponent(jButtonPrikaziPoruke))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPokreniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPokreniActionPerformed
        ps = new PokreniServer();
        ps.start();
        jButtonPokreni.setEnabled(false);
        jButtonZaustavi.setEnabled(true);
    }//GEN-LAST:event_jButtonPokreniActionPerformed

    private void jButtonZaustaviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZaustaviActionPerformed
        ps.zaustaviServer();
        jButtonPokreni.setEnabled(true);
        jButtonZaustavi.setEnabled(false);
    }//GEN-LAST:event_jButtonZaustaviActionPerformed

    private void jButtonUnesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUnesiActionPerformed
        UnosKorisnikaForma ukf = new UnosKorisnikaForma(this, rootPaneCheckingEnabled);
        ukf.setVisible(true);
  
    }//GEN-LAST:event_jButtonUnesiActionPerformed

    private void jButtonPrikaziPorukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrikaziPorukeActionPerformed
        List<Poruka> poruke = Controller.getInstance().vratiPoruke();
        ModelTabelePoruka mtp = new ModelTabelePoruka(poruke);
        jTablePoruke.setModel(mtp);
    }//GEN-LAST:event_jButtonPrikaziPorukeActionPerformed

    private void jTablePorukeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePorukeMouseClicked
        JTable tabela = (JTable) evt.getSource();
        Point p = evt.getPoint();
        int red = tabela.rowAtPoint(p);
        
        ModelTabelePoruka mtp = (ModelTabelePoruka) jTablePoruke.getModel();
        String teskt = mtp.getLista().get(red).getTekst();
        JOptionPane.showMessageDialog(null, teskt);
    }//GEN-LAST:event_jTablePorukeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerskaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerskaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPokreni;
    private javax.swing.JButton jButtonPrikaziPoruke;
    private javax.swing.JButton jButtonUnesi;
    private javax.swing.JButton jButtonZaustavi;
    private javax.swing.JLabel jLabelAdmin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePoruke;
    // End of variables declaration//GEN-END:variables
}
